AWSTemplateFormatVersion: 2010-09-09
Description: Firefly AWS Integration
Mappings:
  FireflyEnvironment:
    env:
      organizationID: "094724549126"
      SnsNameForConfirmCustomerDeployment: "handle-customer-actions"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Parameters:
          - ExternalID
    ParameterLabels:
      ExternalID:
        default: ExternalID
Parameters:
  ExternalID:
    Description: >-
      The cross-account access role created by the stack will use this value for
      its ExternalID. Do not change this value!
    Type: String
    MinLength: '2'
    MaxLength: '1224'
    AllowedPattern: '[\w+=,.@:\/-]*'
    ConstraintDescription: 'Invalid ExternalID value.  Must match pattern [\w+=,.@:\/-]*'
Conditions: {}
Resources:
  FireflyReadonlyPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: [
              'apigateway:GET',
              'cloudwatch:ListDashboards',
              'cloudwatch:GetDashboard',
              'codebuild:BatchGetProjects',
              'ec2:SearchTransitGatewayRoutes',
              'eks:ListNodegroups',
              'eks:ListFargateProfiles',
              'eks:ListTagsForResource',
              'eks:DescribeNodegroup',
              'eks:DescribeFargateProfile',
              'states:DescribeStateMachine',
              'states:ListStateMachines',
              'states:ListTagsForResource',
              'sns:ListSubscriptionsByTopic',
              'sns:ListTopics',
              'sns:ListSubscriptions',
              'ses:GetIdentityMailFromDomainAttributes',
              'ses:GetIdentityVerificationAttributes',
              'sns:GetSubscriptionAttributes',
              'ses:GetIdentityDkimAttributes',
              'ses:ListIdentities',
              'elasticfilesystem:DescribeLifecycleConfiguration',
              'ecr-public:ListTagsForResource',
              'ecr:DescribeRepositories',
              'appconfig:ListApplications',
              'appconfig:ListTagsForResource',
              'eks:ListIdentityProviderConfigs',
              'eks:DescribeIdentityProviderConfig',
              'eks:ListAddons',
              'eks:DescribeAddon',
              'elasticfilesystem:DescribeAccessPoints',
              'elasticfilesystem:ListTagsForResource',
              's3:ListBucket'
              ]
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource:
              - 'arn:aws:s3:::*/*.tfstate'
  FireflyCrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'firefly-caa-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !FindInMap
                    - FireflyEnvironment
                    - env
                    - organizationID
                  - ':root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalID
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
        - 'arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess'
        - !Ref FireflyReadonlyPolicy
Outputs:
  RoleARN:
    Description: >-
      Cross-account access role ARN to share with Firefly
      integration
    Value: !GetAtt
      - FireflyCrossAccountAccessRole
      - Arn
  ExternalID:
    Description: ExternalID to share with Firefly
    Value: !Ref ExternalID
  TemplateVersion:
    Description: gofirefly.io template version
    Value: 1.0.0
