AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RoleArn:
    Description: 'Please input your role arn'
    Type: String
    ConstraintDescription: Please input your role arn

  BucketName:
    Description: 'Please input your S3 Bucket name to grant permission'
    Type: String
    ConstraintDescription: Please input your S3 Bucket name to grant permission

Resources:

  BucketReadPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:

          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource:
              - !Join [':', ['arn:aws:s3::', !Ref 'BucketName']]
              - "Fn::Join": [
                "", [
                !Join [':', ['arn:aws:s3::', !Ref 'BucketName']],
                "/*"
              ]
              ]

      Roles:
        - !Select [1, !Split ["/", !Ref RoleArn]]